$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: model-deployment
endpoint_name: end-2-end-endpoint
model: azureml:prod-model@latest
instance_type: Standard_F4s_v2
instance_count: 1
