name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Clone the GitHub repository
      uses: actions/checkout@v2
      with:
        repository: dssaenzml/azure-dl-sol
    - name: Trigger Azure Machine Learning job
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az ml job create --file ./azure-dl-sol/src/job.yml
