name: Feature-based development trigger

on:
  pull:
    branches:
      - main
      
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
