name: Main branch push trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - src/job.yml
      - src/prod-job.yml
jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: az ml job create --file src/job.yml -g ds-cert -w ds-cert --stream
  production:
    runs-on: ubuntu-latest
    needs: experiment
    if: ${{ success() }}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: az ml job create --file src/prod-job.yml -g ds-cert -w ds-cert --stream
